In [1]:
import numpy as np
import pandas as pd

# Лекция 4. Numpy

In [2]:
df=pd.read_excel('moviedb.xlsx')
df.head()

Unnamed: 0                                        title  \
0        7495  Пираты Карибского моря: На странных берегах   
1        6783                              Мстители: Финал   
2        6308                          Лига справедливости   
3        6781                Мстители: Война бесконечности   
4        7494        Пираты Карибского моря: На краю света   

               release  runtime       budget       revenue lang       genre1  \
0  2011-05-14 00:00:00    136.0  380000000.0  1.045714e+09   en  приключения   
1  2019-04-24 00:00:00    182.0  356000000.0  2.797801e+09   en  приключения   
2                43054    110.0  300000000.0  6.579243e+08   en       боевик   
3  2018-04-25 00:00:00    149.0  300000000.0  2.046240e+09   en  приключения   
4                39221    169.0  300000000.0  9.610000e+08   en  приключения   

        genre2 country1  ...                   writer  \
0       боевик       GB  ...                      NaN   
1   фантастика       US  ...           Marvel Studios   
2  приключения       GB  ...             Chris Terrio   
3       боевик       US  ...           Marvel Studios   
4      фэнтези       US  ...  Jerry Bruckheimer Films   

                   studio1                  studio2            keyword1  \
0     Walt Disney Pictures  Jerry Bruckheimer Films             england   
1                      NaN             space travel         time travel   
2                DC Comics         DC Entertainment           dc comics   
3                      NaN                    magic           sacrifice   
4  Second Mate Productions            exotic island  east india company   

             keyword2        keyword3        keyword4        keyword5  \
0               spain             sea         captain          mutiny   
1        time machine          sequel  based on comic  alien invasion   
2           superhero  based on comic     super power  superhero team   
3           superhero  based on comic           space     battlefield   
4  love of one's life         traitor       shipwreck    strong woman   

              keyword6    rating  
0                sword  6.500000  
1       superhero team  7.873993  
2  aftercreditsstinger  6.307256  
3             genocide  7.963608  
4            singapore  7.200000  

[5 rows x 27 columns]

## Numpy - библиотека для работы с массивами

In [6]:
a = np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [74]:
# список продолжительность фильма
budget = list(df['budget'].dropna().values)*1000
print(type(budget))
print(len(budget))

<class 'list'>
4119000


In [76]:
budget_np = np.array(budget)
print(type(budget_np))
print(budget_np.shape)

<class 'numpy.ndarray'>
(4119000,)


In [94]:
%%timeit
sum(budget)/len(budget)

244 ms ± 7.82 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [93]:
%%timeit
budget_np.mean()

6.26 ms ± 119 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [104]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([1.5, 2.6, 3.1, 4.8, 5.1], dtype=float)

In [96]:
c = np.arange(start=10, stop=20, step=2) 
print(c)

[10 12 14 16 18]


In [99]:
print(a)
print(b)
print(a + b) #сумма
print(a - b) #разность
print(a*b) #перемножение

[1 2 3 4 5]
[1.5 2.6 3.1 4.8 5. ]
[ 2.5  4.6  6.1  8.8 10. ]
[-0.5 -0.6 -0.1 -0.8  0. ]
[ 1.5  5.2  9.3 19.2 25. ]


In [105]:
from numpy.linalg import norm
print('Расстояние между векторами a и b: {norm}'.format(norm = norm(a-b, ord=1)))

Расстояние между векторами a и b: 2.0999999999999996


In [106]:
print('Скалярное произведение a and b: {}'.format(np.dot(a, b)))
print('Скалярное произведение a and b: {}'.format(a.dot(b)))

Скалярное произведение a and b: 60.7
Скалярное произведение a and b: 60.7


## Матрицы

In [107]:
a = np.array([[1, 2, 3], [2, 5, 6], [6, 7, 4]])
print(a)

[[1 2 3]
 [2 5 6]
 [6 7 4]]


In [108]:
b = np.eye(5)
print(b)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [109]:
c = np.ones((7, 5))
print(c)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [110]:
v = np.arange(0, 24, 2)
print(v)
d = v.reshape((3, 4))
print(d)

[ 0  2  4  6  8 10 12 14 16 18 20 22]
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]


In [111]:
print(d)
print(d[2, 1])
print(d[1, :])
print(d[:, 3])

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
18
[ 8 10 12 14]
[ 6 14 22]


In [112]:
a = np.array([[1, 0], [0, 1]])
b = np.array([[4, 1], [2, 2]])
r1 = np.dot(a, b)
r2 = a.dot(b)

In [113]:
print('Matrix a:\n', a)
print('Matrix b:\n', b)
print('Multiplication, 1 method:\n', r1)
print('Multiplication, 2 method:\n', r2)

Matrix a:
 [[1 0]
 [0 1]]
Matrix b:
 [[4 1]
 [2 2]]
Multiplication, 1 method:
 [[4 1]
 [2 2]]
Multiplication, 2 method:
 [[4 1]
 [2 2]]


In [114]:
c = np.array([1, 2])
r3 = b.dot(c)

In [115]:
print('Matrix a:\n', a)
print('Vector c:\n', c)
print('Multiplication:\n', r3)

Matrix a:
 [[1 0]
 [0 1]]
Vector c:
 [1 2]
Multiplication:
 [6 6]


In [116]:
a = np.array([[1, 2], [3, 4]])
b = np.transpose(a)
c = a.T

In [117]:
print('Matrix a:\n', a)
print('Transposed matrix:\n', b)
print('Transposed matrix:\n', c)

Matrix a:
 [[1 2]
 [3 4]]
Transposed matrix:
 [[1 3]
 [2 4]]
Transposed matrix:
 [[1 3]
 [2 4]]


In [118]:
a = np.array([[1, 2, 1], [1, 1, 4], [2, 3, 6]], dtype=np.float32)
det = np.linalg.det(a)

In [119]:
print('Matrix a:\n', a)
print('Determinant of a:\n', det)

Matrix a:
 [[1. 2. 1.]
 [1. 1. 4.]
 [2. 3. 6.]]
Determinant of a:
 -1.0


In [120]:
a = np.array([[1, 2, 3], [1, 1, 1], [2, 2, 2]])
r = np.linalg.matrix_rank(a)
print('Matrix a:\n', a)
print('Rank of a:\n', r)

Matrix a:
 [[1 2 3]
 [1 1 1]
 [2 2 2]]
Rank of a:
 2


In [121]:
a = np.array([1, 2, 3])
b = np.array([1, 1, 1])
c = np.array([2, 3, 5])
m = np.array([a, b, c])

print(np.linalg.matrix_rank(m) == m.shape[0])

True


задача 1 - сводная таблица (строки - жанры, столбцы - топ 10 популярных студий, значения - средний рейтинг)